// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffqjmabdpqoltsjfhadt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmcWptYWJkcHFvbHRzamZoYWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNDMyMDgsImV4cCI6MjA1OTgxOTIwOH0.KYY113tanmQPhIOlERIHrNfauPVZR0RVxjf8KqF2Z88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);